"""add_missing_tables_and_columns

Revision ID: 370b5d0a07fa
Revises: 0cd7d2eecabe
Create Date: 2026-05-07 10:13:42.071330

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '370b5d0a07fa'
down_revision: Union[str, None] = '0cd7d2eecabe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.create_unique_constraint(None, 'image', ['id'])
    op.add_column('user', sa.Column('profile_image_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_profile_image_id'), 'user', ['profile_image_id'], unique=False)
    op.create_foreign_key('fk_user_profile_image_id', 'user', 'image', ['profile_image_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_profile_image_id', 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_profile_image_id'), table_name='user')
    op.drop_column('user', 'profile_image_id')
    op.drop_constraint(None, 'image', type_='unique')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
