"""add status

Revision ID: c35f88f56a91
Revises: e6f7a8b9c0d1
Create Date: 2026-05-20 14:14:14.290890

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c35f88f56a91'
down_revision: Union[str, None] = 'e6f7a8b9c0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('customer', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('customer', sa.Column('longitude', sa.Float(), nullable=True))
    op.alter_column('customer', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('customer', 'meter_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('customer', 'phone')
    op.create_unique_constraint(None, 'token_blacklist', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token_blacklist', type_='unique')
    op.add_column('customer', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('customer', 'meter_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('customer', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('customer', 'longitude')
    op.drop_column('customer', 'latitude')
    op.drop_column('customer', 'status')
    # ### end Alembic commands ###
