"""change_rt_rw_meter_to_numeric

Revision ID: f9531a2845d5
Revises: b2c3d4e5f6a7
Create Date: 2026-06-04 15:09:30.969510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9531a2845d5'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use direct connection to avoid transaction issues
    connection = op.get_bind()
    
    # Drop defaults that might cause issues during type conversion
    connection.execute(sa.text("ALTER TABLE customer ALTER COLUMN rt DROP DEFAULT"))
    connection.execute(sa.text("ALTER TABLE customer ALTER COLUMN rw DROP DEFAULT"))
    
    # 1. Update bill table
    connection.execute(sa.text("ALTER TABLE bill ALTER COLUMN meter_start TYPE double precision USING meter_start::double precision"))
    connection.execute(sa.text("ALTER TABLE bill ALTER COLUMN meter_end TYPE double precision USING meter_end::double precision"))
    connection.execute(sa.text("ALTER TABLE bill ALTER COLUMN usage TYPE double precision USING usage::double precision"))
    
    # Clean and update customer table
    connection.execute(sa.text("UPDATE customer SET rt = '1' WHERE rt !~ '^[0-9]+$' OR rt IS NULL OR rt = ''"))
    connection.execute(sa.text("UPDATE customer SET rw = '1' WHERE rw !~ '^[0-9]+$' OR rw IS NULL OR rw = ''"))
    
    # Handle duplicate meter_numbers before making it unique
    # Append the ID to the meter_number to make it unique if duplicates are found
    connection.execute(sa.text("""
        UPDATE customer 
        SET meter_number = id::text 
        WHERE meter_number IN (
            SELECT meter_number FROM customer 
            GROUP BY meter_number HAVING COUNT(*) > 1
        ) OR meter_number !~ '^[0-9.]+$' OR meter_number IS NULL OR meter_number = ''
    """))
    
    connection.execute(sa.text("ALTER TABLE customer ALTER COLUMN rt TYPE integer USING rt::integer"))
    connection.execute(sa.text("ALTER TABLE customer ALTER COLUMN rw TYPE integer USING rw::integer"))
    connection.execute(sa.text("ALTER TABLE customer ALTER COLUMN meter_number TYPE double precision USING meter_number::double precision"))
    
    # Check if index exists before creating
    op.create_index(op.f('ix_customer_meter_number'), 'customer', ['meter_number'], unique=True)
    
    # 3. Update meter_reading table
    connection.execute(sa.text("ALTER TABLE meter_reading ALTER COLUMN current_meter TYPE double precision USING current_meter::double precision"))
    connection.execute(sa.text("ALTER TABLE meter_reading ALTER COLUMN previous_meter TYPE double precision USING previous_meter::double precision"))
    connection.execute(sa.text("ALTER TABLE meter_reading ALTER COLUMN usage TYPE double precision USING usage::double precision"))
    
    # 4. Clean and update officer_area table
    connection.execute(sa.text("UPDATE officer_area SET rt = '1' WHERE rt !~ '^[0-9]+$' OR rt IS NULL OR rt = ''"))
    connection.execute(sa.text("UPDATE officer_area SET rw = '1' WHERE rw !~ '^[0-9]+$' OR rw IS NULL OR rw = ''"))
    
    connection.execute(sa.text("ALTER TABLE officer_area ALTER COLUMN rt TYPE integer USING rt::integer"))
    connection.execute(sa.text("ALTER TABLE officer_area ALTER COLUMN rw TYPE integer USING rw::integer"))
    
    op.create_index(op.f('ix_officer_area_user_id'), 'officer_area', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'officer_area', type_='foreignkey')
    op.drop_index(op.f('ix_officer_area_user_id'), table_name='officer_area')
    op.create_unique_constraint(op.f('officer_area_user_id_rt_rw_key'), 'officer_area', ['user_id', 'rt', 'rw'], postgresql_nulls_not_distinct=False)
    op.alter_column('officer_area', 'rw',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('officer_area', 'rt',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('meter_reading', 'usage',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('meter_reading', 'previous_meter',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('meter_reading', 'current_meter',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_customer_meter_number'), table_name='customer')
    op.alter_column('customer', 'meter_number',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('customer', 'rw',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('customer', 'rt',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('bill', 'usage',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('bill', 'meter_end',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('bill', 'meter_start',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
